---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zyx.
--- DateTime: 2020/7/9 上午1:28
---
function diving_board(shorter, longer, k)

    if k == 0 then
        return {}
    end
    local subtraction = longer - shorter;
    local min = shorter * k;
    if subtraction > 0 then
        local result = { min };
        while k > 0 do
            table.insert(result, result[#result] + subtraction)
            k = k - 1
        end
        return result;
    else
        return { min };
    end

end
print("[", table.concat(diving_board(5, 95, 983), ","), "]")