---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zyx.
--- DateTime: 2020/8/18 12:09 上午
---
function flood_fill(image, sr, sc, new_color)
    local origin_color = image[sr][sc];
    local records = {}
    for row = 1, #image do
        local row_array = {}
        for col = 1, #image[row] do
            row_array[col] = 0;
        end
        records[row] = row_array;
    end
    flood_fill(records, image, sr, sc, origin_color, new_color);
    return image;
end
function flood_fill(records, image, sr, sc, origin_color, new_color)
    if sr >= 0 and sr < #image and sc >= 0 and sc < #image[1]
            and image[sr][sc] == origin_color and records[sr][sc] == 0 then
        image[sr][sc] = new_color;
        records[sr][sc] = 1;
        flood_fill(records, image, sr - 1, sc, origin_color, new_color);
        flood_fill(records, image, sr + 1, sc, origin_color, new_color);
        flood_fill(records, image, sr, sc - 1, origin_color, new_color);
        flood_fill(records, image, sr, sc + 1, origin_color, new_color);
    end
end

