---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zyx.
--- DateTime: 2020/7/9 上午1:48
---
function wc(string)
    local count, is_word_flag = 0, false
    for index = 1, #string do
        if not string:sub(index, index):find("^[%w_-]$") and is_word_flag then
            count = count + 1
            is_word_flag = false
        end
        if string:sub(index, index):find("^[%w_-]$") and not is_word_flag then
            is_word_flag = true
        end
    end
    return count

end
print(wc("      hello    world     "))